# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import my_thread


class Ui_Dialog(QtWidgets.QDialog):
    def setupUi(self, df):
        super().__init__()
        self.df = df

        self.resize(1203, 783)
        self.show_frame = QtWidgets.QLabel(self)
        self.show_frame.setGeometry(QtCore.QRect(60, 10, 640, 480))
        self.show_frame.setText("")
        self.show_frame.setObjectName("show_frame")
        self.frame_value = QtWidgets.QTableView(self)
        self.frame_value.setGeometry(QtCore.QRect(100, 500, 571, 192))
        self.frame_value.setObjectName("frame_value")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        th = my_thread.Thread(self, self.df)
        th.changePixmap.connect(self.setImage)
        th.start()

        # self.frame_value.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    
    @my_thread.pyqtSlot(my_thread.QImage)
    def setImage(self, image):
        self.show_frame.setPixmap(my_thread.QPixmap.fromImage(image))
